site_name: Reference System Documentation
site_url: https://ros-realtime.github.io/reference-system/
site_author: Evan Flynn
repo_url: https://github.com/ros-realtime/reference-system.git
theme:
  name: 'material'
plugins:
  - search
extra:
  version:
    provider: mike
nav:
  - Home: index.md
  - Reports: Reports
  - Classes: Classes
  - Namespaces: Namespaces
  - Modules: Modules
  - Files: Files
  - Related Pages: Pages
