site_name: Reference System Documentation
docs_dir: markdown
theme:
  name: 'material'
plugins:
  - search
nav:
  - Home: reference-system/Pages/md_README
  - Classes: reference-system/Classes
  - Namespaces: reference-system/Namespaces
  - Modules: reference-system/Modules
  - Files: reference-system/Files
  - Related Pages: reference-system/Pages
  - Examples: reference-system/Examples
