name: Build Documentation

on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]
    branches: [main]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup workspace
        # TODO(flynneva): make this a variable and use it at every step
        run: mkdir -p ros2_ws/src/reference_system
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros2_ws/src/reference_system
      - name: Run Doxygen on source
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'ros2_ws/src/reference_system'
          doxyfile-path: '.doxygen/Doxyfile'
      - name: Upload Doxygen XML
        uses: actions/upload-artifact@v3
        with:
          name: doxygen_xml
          path: ros2_ws/src/reference_system/docs/xml
          retention-days: 30
  generate-doxybook2:
    runs-on: ubuntu-latest
    needs: generate-doxygen
    steps:
      - name: Setup workspace
        run: mkdir -p ros2_ws/src/reference_system
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros2_ws/src/reference_system
      - name: Download Doxygen XML
        uses: actions/download-artifact@v3
        with:
          name: doxygen_xml
          path: ros2_ws/src/reference_system/docs/xml
      - name: Build API Reference
        run: |
          mkdir ros2_ws/src/reference_system/docs/api-reference
          wget https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-linux-amd64-v1.4.0.zip
          sudo apt-get install unzip
          unzip doxybook2-linux-amd64-v1.4.0.zip
          ./bin/doxybook2 --input ros2_ws/src/reference_system/docs/xml \
            --output ros2_ws/src/reference_system/docs/api-reference \
            --config ros2_ws/src/reference_system/docs/doxybook2_config.json
      - name: Upload API Reference
        uses: actions/upload-artifact@v3
        with:
          name: api_reference
          path: 'ros2_ws/src/reference_system/docs/api-reference'
          retention-days: 30
  build-mkdocs:
    runs-on: ubuntu-latest
    # Only run if doxybook was generated
    needs: generate-doxybook2
    steps:
      - name: Setup workspace
        # TODO(flynneva): make this a variable and use it at every step
        run: mkdir -p ros2_ws/src/reference_system
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros2_ws/src/reference_system
      - name: Download API Reference
        uses: actions/download-artifact@v3
        with:
          name: api_reference
          path: 'ros2_ws/src/reference_system/docs/api-reference'
      - name: Build mkdocs site
        run: |
          cd ros2_ws/src/reference_system
          # ensure gh-pages git history is fetched
          git fetch origin gh-pages --depth=1
          sudo apt-get update -y
          # install mkdocs dependencies
          pip3 install -r docs/requirements.txt
          # build site
          mkdocs build
      - name: Upload docs site
        uses: actions/upload-artifact@v3
        with:
          name: reference_system_site
          path: ros2_ws/src/reference_system/site
