name: Build Documentation

on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]
    branches: [main]
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  WORKSPACE_PATH: ros2_ws/src/reference_system

jobs:
  generate-doxygen:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
    steps:
      - name: Make sure output directory exists
        run: mkdir -p ${{ env.WORKSPACE_PATH }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE_PATH }}
      - name: Run Doxygen on source
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: ${{ env.WORKSPACE_PATH }}
          doxyfile-path: '.doxygen/Doxyfile'
      - name: Upload Doxygen XML
        uses: actions/upload-artifact@v3
        with:
          name: doxygen_xml
          path: ${{ env.WORKSPACE_PATH }}/docs/xml
          retention-days: 30
  generate-doxybook2:
    runs-on: ubuntu-latest
    needs: generate-doxygen
    steps:
      - name: Make sure output directory exists
        run: mkdir -p ${{ env.WORKSPACE_PATH }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE_PATH }}
      - name: Generate doxybook2 markdown
        uses: ./ros2_ws/src/reference_system/.github/actions/generate-doxybook
        with:
          input-doxygen-artifact: doxygen_xml
          doxygen-artifact-extraction-path: ${{ env.WORKSPACE_PATH }}/docs/xml
          doxybook2-version: v1.4.0
          doxybook2-config-path: ${{ env.WORKSPACE_PATH }}/docs/doxybook2_config.json
          output-path: ${{ env.WORKSPACE_PATH }}/docs/api-reference
          base-url: /reference-system/latest/api-reference/
      - name: Upload API Reference
        uses: actions/upload-artifact@v3
        with:
          name: api_reference
          path: ${{ env.WORKSPACE_PATH }}/docs/api-reference
          retention-days: 30
  build-mkdocs:
    runs-on: ubuntu-latest
    needs: generate-doxybook2
    steps:
      - name: Make sure output directory exists
        run: mkdir -p ${{ env.WORKSPACE_PATH }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE_PATH }}
      - name: Download API Reference
        uses: actions/download-artifact@v3
        with:
          name: api_reference
          path: ${{ env.WORKSPACE_PATH }}/docs/api-reference
      - name: Build mkdocs site
        run: |
          cd ${{ env.WORKSPACE_PATH }}
          # ensure gh-pages git history is fetched
          git fetch origin gh-pages --depth=1
          sudo apt-get update -y
          # install mkdocs dependencies
          python3 -m pip install -r docs/requirements.txt
          # build site
          mkdocs build
      - name: Upload docs site
        uses: actions/upload-artifact@v3
        with:
          name: reference_system_site
          path: ${{ env.WORKSPACE_PATH }}/site
