name: Generate documentation site
on:
  push:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deply-docs:
    runs-on: ubuntu-latest
    # Only run if doxybook was generated
    needs: generate-doxybook
    steps:
      - name: Download Doxybook2 markdown
        uses: actions/download-artifact@v3
        with:
          name: doxybook_markdown
      - name: build mkdocs site
        run: |
          cd ros2_ws/src/reference_system/
          # ensure gh-pages git history is fetched
          git fetch origin gh-pages --depth=1
          cd docs
          apt-get update -y
          # install mkdocs dependencies
          pip3 install mkdocs mkdocs-material mike
          # since this workflow is triggered by a push to main, set to `latest` alias
          mike deploy --push --update-aliases main latest
