# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - rolling
        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - ros_distribution: foxy
            docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-latest
          # Galactic Geochelone (May 2021 - November 2022)
          - ros_distribution: galactic
            docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
          # Rolling Ridley  (June 2020 - Present)
          - ros_distribution: rolling
            docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    container:
      image: ${{ matrix.docker_image }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup workspace
        run: mkdir -p ros2_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros2_ws/src
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: autoware_reference_system
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
