name: Deploy Documentation
on:
  # Only deploy docs if build docs workflow passes
  workflow_run:
    workflows:
      - "Build Documentation"
      # - "Run Benchmarks"
    types:
      - completed
    branches:
      - main  # only deploy if docs built are from main (do not deploy pr doc builds)
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# TODO: reusing envs across workflows is not supported yet for gh actions
# re-evaluate once available (something like `include` or `import` another yaml would work)
env:
  WORKSPACE_PATH: ros2_ws/src/reference_system

jobs:
  deploy-mkdocs:
    runs-on: ubuntu-latest
    # Only run job if docs build workflow succeeds
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup workspace
        # TODO(flynneva): make this a variable and use it at every step
        run: mkdir -p ${{ env.WORKSPACE_PATH }}
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORKSPACE_PATH }}
      - name: Download API reference
        uses: dawidd6/action-download-artifact@v2
        with:
          name: api_reference
          path: '${{ env.WORKSPACE_PATH }}/docs/api-reference'
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: Download Foxy reports
        continue-on-error: true  # Still publish docs even if reports are not available
        uses: dawidd6/action-download-artifact@v2
        with:
          name: benchmark_reports_foxy  # TODO: make this a list and iterate over it
          path: '${{ env.WORKSPACE_PATH }}/docs/reports/foxy'
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: Download Galactic reports
        continue-on-error: true  # Still publish docs even if reports are not available
        uses: dawidd6/action-download-artifact@v2
        with:
          name: benchmark_reports_galactic  # TODO: make this a list and iterate over it
          path: '${{ env.WORKSPACE_PATH }}/docs/reports/galactic'
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: Download Rolling reports
        continue-on-error: true  # Still publish docs even if reports are not available
        uses: dawidd6/action-download-artifact@v2
        with:
          name: benchmark_reports_rolling  # TODO: make this a list and iterate over it
          path: '${{ env.WORKSPACE_PATH }}/docs/reports/rolling'
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: Deploy mkdocs site
        run: |
          cd ${{ env.WORKSPACE_PATH }}
          # ensure gh-pages git history is fetched
          git fetch origin gh-pages --depth=1
          sudo apt-get update -y
          # install docs dependencies
          python3 -m pip install -r docs/requirements.txt
          # TODO: mike rebuilds entire site, instead we should
          # skip the build and download site artifact from previous workflow
          if [ -z ${{ github.event.release.tag_name }}]; then
            export NEW_VERSION=main
          else
            export NEW_VERSION=${{ github.event.release.tag_name }}
          fi
          git config user.name doc-bot
          git config user.email doc-bot@ros-realtime.com
          mike deploy --push --update-aliases $NEW_VERSION latest
