name: Generate Doxybook2

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  generate-doxybook2:
    runs-on: ubuntu-latest
    needs: generate_doxygen
    steps:
      - name: Download Doxygen XML
        uses: actions/download-artifact@v3
        with:
          name: doxygen_xml
      - name: Build Doxybook2
        run: |
          mkdir ros2_ws/src/reference_system/docs/markdown
          wget https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-linux-amd64-v1.4.0.zip
          apt-get install unzip
          unzip doxybook2-linux-amd64-v1.4.0.zip
          ./bin/doxybook2 --input ros2_ws/src/reference_system/docs/xml \
            --output ros2_ws/src/reference_system/docs/markdown \
            --config ros2_ws/src/reference_system/docs/doxybook2_config.json
      - name: Upload Doxybook2 markdown
        uses: actions/upload-artifact@v3
        with:
          name: doxybook_markdown
          path: 'ros2_ws/src/reference_system/docs/markdown'
          retention-days: 30