name: Generate Doxygen XML 

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Only build docs if build / test jobs were successful
    needs: build_and_test
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup workspace
        # TODO(flynneva): make this a variable and use it at every step
        run: mkdir -p ros2_ws/src/reference_system
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros2_ws/src/reference_system
      - name: Run Doxygen on source
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'ros2_ws/src/reference_system'
          doxyfile-path: '.doxygen/Doxyfile'
      - name: Upload Doxygen XML
        uses: actions/upload-artifact@v3
        with:
          name: doxygen_xml
          path: 'ros2_ws/src/reference_system/docs/xml'
          retention-days: 30